# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'DYZB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DYZB
  pod 'SnapKit'
  pod 'Alamofire'

  target 'DYZBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DYZBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
